apiVersion: v1
kind: Pod
spec:
  containers:
    - name: azure-pyspark
      env:
      - name: SCONE_LAS_ADDR
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      resources:
        limits:
          cpu: "8"
          sgx.intel.com/enclave: 1
          memory: "10Gi"
        requests:
          cpu: "4"
          sgx.intel.com/enclave: 1
          memory: "6Gi"
