apiVersion: v1
kind: Pod
spec:
  containers:
    - name: azure-pyspark
      env:
      - name: SCONE_LAS_ADDR
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      securityContext:
        privileged: true
      resources:
        limits:
          cpu: "8"
          memory: "10Gi"
        requests:
          cpu: "4"
          memory: "10Gi"
