apiVersion: v1
kind: Pod
metadata:
  name: attestationpy
  labels:
    app: attestationpy
spec:
  containers:
  - image: nramar/cvmpythonattestapi:latest
    imagePullPolicy: IfNotPresent
    name: attestation-client-python
    volumeMounts:
      - mountPath: /sys/kernel/security
        name: tcg
      - mountPath: /dev/tpmrm0
        name: tpmrm0
    securityContext:
      privileged: true
  volumes:
    - name: tcg
      hostPath:
        path: /sys/kernel/security
    - name: tpmrm0
      hostPath:
        path: /dev/tpmrm0
  restartPolicy: Always
